runtime: php72

handlers:
# Serve images, javascript, html, as static resources.
- url: /(.+\.(css|html|GIF|PNG|JPG|gif|png|jpg|js|ico))$
  static_files: \1
  upload: .+\.(css|html|GIF|PNG|JPG|gif|png|jpg|js|ico)$
  secure: always
  redirect_http_response_code: 301

# default url is index.html
- url: /
  script: auto
  secure: always
  redirect_http_response_code: 301

# Serve php scripts.
- url: /(.+\.php).*
  script: auto
  secure: always
  redirect_http_response_code: 301

automatic_scaling:
  max_instances: 1

